### ISSUE TITLE
Is there a guide for how to set up embedded records with Ember-Data?

### ISSUE THREAD

**Issue by NullVoxPopuli** [spieker/active_model_serializers-jsonapi_embedded_records_deserializer#2]
I'm using Ember-Data, and would like to use your AMS extension for some cart/line-item bulk create functionality :-)

I guess, is there a setting or adapter I need to modify to optionally embed records upon a save in ember?

**Comment by spieker** [comment]
Maybe this helps: http://ember-twiddle.com/24893e21e87f065b1d48

**Comment by NullVoxPopuli** [comment]
that does help, thanks!
