### ISSUE TITLE
How do I use this with Rails + jsonapi-resources?

### ISSUE THREAD

**Issue by lynndylanhurley** [spieker/active_model_serializers-jsonapi_embedded_records_deserializer#5]
Can you provide an example how this should be used with a Rails + jsonapi-resources project?

I've included the gem in my `Gemfile`, but when I try to use `ActiveModelSerializers::Deserialization.jsonapi_parse` in my controllers, the `Deserialization` module is undefined. 

I have a few questions:
- Do I need to `require` this gem in my project somewhere? If so, where?
- Is there a way to get jsonapi-resources to use this serializer by default, or do I need to manually call `ActiveModelSerializers::Deserialization.jsonapi_parse` in each of my controllers that need it?

Thanks!

**Comment by spieker** [comment]
It's not meant for use with jsonapi-resources, it's an extension for active_model_serializers.
