### ISSUE TITLE
Serialization of nested resources

### ISSUE THREAD

**Issue by jmarceli** [spieker/active_model_serializers-jsonapi_embedded_records_deserializer#6]
It would be nice to have an option to serialize existing objects to correct format (handled by this deserializer). Here is my issue https://github.com/rails-api/active_model_serializers/issues/1875#issuecomment-237915353.
Is it currently implemented?

**Comment by spieker** [comment]
I actually don't know if AMS is able to serialize into the corresponding format. I'm using EmberJS and have created an example how to implement a serializer (https://ember-twiddle.com/24893e21e87f065b1d48) which works with this Gem but I'm not planning to implement a serialization part for this Gem for AMS.

**Comment by jmarceli** [comment]
It is after a couple of modifications. Here is my current solution https://github.com/rails-api/active_model_serializers/issues/1875#issuecomment-238013893. Seems to be working well.
